version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 table_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=table_db
      - POSTGRES_USER=table_user
      - POSTGRES_PASSWORD=table_password

volumes:
  postgres_data:
  static_volume:
  media_volume: 