# Generated by Django 5.0.2 on 2025-03-02 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(blank=True, max_length=255, verbose_name='Контрагент')),
                ('payment_purpose', models.CharField(blank=True, max_length=255, verbose_name='Банковское назначение платежа')),
                ('internal_purpose', models.CharField(max_length=255, verbose_name='Внутреннее назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255, verbose_name='Название листа')),
                ('file', models.FileField(upload_to='excel_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'ods'])], verbose_name='Excel файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('data_json', models.JSONField(default=dict, verbose_name='Данные в JSON')),
            ],
            options={
                'verbose_name': 'Данные таблицы',
                'verbose_name_plural': 'Данные таблиц',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
