# Generated by Django 5.1.6 on 2025-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='internal_purpose',
            field=models.CharField(choices=[('Ozon', 'Ozon'), ('ЯМ (Яндекс Маркет)', 'ЯМ (Яндекс Маркет)'), ('WB', 'WB'), ('ПП (Прямые продажи)', 'ПП (Прямые продажи)'), ('Другие направления', 'Другие направления'), ('(-) ЗК (Затраты Компании)', '(-) ЗК (Затраты Компании)'), ('(-) ДБН (Другие бизнес направления)', '(-) ДБН (Другие бизнес направления)'), ('(-) ЛТ (Личные Траты)', '(-) ЛТ (Личные Траты)'), ('(-) ВС (Вывод себе на счет)', '(-) ВС (Вывод себе на счет)'), ('A  (Amazon)', 'A  (Amazon)'), ('ЛД (личные доходы)', 'ЛД (личные доходы)'), ('(-) Ф', '(-) Ф'), ('(-) GB', '(-) GB'), ('Переводы', 'Переводы')], max_length=255, verbose_name='Внутреннее назначение'),
        ),
    ]
