# Generated by Django 5.1.6 on 2025-03-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0002_alter_filter_internal_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='internal_purpose',
            field=models.CharField(choices=[('Ozon', 'Ozon'), ('ЯМ', 'ЯМ (Яндекс Маркет)'), ('WB', 'WB'), ('ПП', 'ПП (Прямые продажи)'), ('Другие направления', 'Другие направления'), ('(-) ЗК', '(-) ЗК (Затраты Компании)'), ('(-) ДБН', '(-) ДБН (Другие бизнес направления)'), ('(-) ЛТ', '(-) ЛТ (Личные Траты)'), ('(-) ВС', '(-) ВС (Вывод себе на счет)'), ('A', 'A (Amazon)'), ('ЛД', 'ЛД (личные доходы)'), ('(-) Ф', '(-) Ф'), ('(-) GB', '(-) GB'), ('Переводы', 'Переводы')], max_length=255, verbose_name='Внутреннее назначение'),
        ),
    ]
