# Generated by Django 5.0.2 on 2025-03-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritual_app', '0004_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='При отсутствии названия будет сгенерировано автоматически', max_length=200, verbose_name='Название'),
        ),
    ]
